### ISSUE TITLE
Can’t change translation

### ISSUE THREAD

**Issue by Michaelwucoc** [NodeBB/nodebb-plugin-customize#15]
![6D5423D6-71A3-4850-9619-26D49C9258A5](https://user-images.githubusercontent.com/110759450/215308689-b396a16d-15cf-438f-a2a5-12359ef6ce60.png)

I can’t find any available settings here…

**Comment by pitaj** [comment]
You need NodeBB v2.8.3 minimum for this plugin to work.

**Comment by Michaelwucoc** [comment]
I want to know how to install the minimum version…Or it needs another plug-in?

**Comment by pitaj** [comment]
https://docs.nodebb.org/configuring/upgrade/

Upgrade to v2.8.5

**Comment by Michaelwucoc** [comment]
Okay. I’ll do it.
