### ISSUE TITLE
Problem with 3.7.4

### ISSUE THREAD

**Issue by ylothar** [NodeBB/nodebb-plugin-customize#18]
I've recently upgraded my NodeBB installation from 1.9.7 to 3.4.7.
Plugin shows me all old definition but UI seems wrong and I can't modify nor insert anything.

![Schermata del 2024-05-01 16-27-42](https://github.com/NodeBB/nodebb-plugin-customize/assets/682247/45a7158d-16dd-4838-af2c-dee7d451fae1)

**Comment by pitaj** [comment]
What version of the plugin is installed? Have you tried rebuilding NodeBB?

**Comment by ylothar** [comment]
- **NodeBB version:** v3.7.4
- **NodeBB git hash:** c26c904ae7a3cbc5529424bbbba943393bd6d0ea
- **NodeJS version:** v20.12.2
- **Installed NodeBB Plugins:**
  * @nodebb/nodebb-plugin-reactions@2.2.2 (installed, enabled)
  * @nodebb/nodebb-plugin-user-level@2.1.2 (installed, enabled)
  * nodebb-plugin-2factor@7.4.0 (installed, enabled)
  * nodebb-plugin-composer-default@10.2.33 (installed, enabled)
  * nodebb-plugin-custom-pages@2.1.0 (installed, enabled)
  * nodebb-plugin-customize@4.0.2 (installed, enabled)
  * nodebb-plugin-dbsearch@6.2.3 (installed, enabled)
  * nodebb-plugin-emoji@5.2.0 (installed, enabled)
  * nodebb-plugin-emoji-android@4.0.0 (installed, enabled)
  * nodebb-plugin-emoji-fontawesome@4.0.0 (installed, enabled)
  * nodebb-plugin-extended-markdown@2.0.1 (installed, enabled)
  * nodebb-plugin-glossary@1.1.0 (installed, enabled)
  * nodebb-plugin-google-analytics@1.1.0 (installed, enabled)
  * nodebb-plugin-link-mentions@1.0.0 (installed, enabled)
  * nodebb-plugin-link-preview@1.3.3 (installed, enabled)
  * nodebb-plugin-markdown@12.2.6 (installed, enabled)
  * nodebb-plugin-mentions@4.4.0 (installed, enabled)
  * nodebb-plugin-newsletter@0.11.0 (installed, enabled)
  * nodebb-plugin-poll@3.1.4 (installed, enabled)
  * nodebb-plugin-question-and-answer@1.2.7 (installed, enabled)
  * nodebb-plugin-recent-cards@3.3.0 (installed, enabled)
  * nodebb-plugin-registration-notification@3.0.0 (installed, enabled)
  * nodebb-plugin-soundpack-default@3.0.1 (installed, enabled)
  * nodebb-plugin-spam-be-gone@2.2.2 (installed, enabled)
  * nodebb-plugin-tenor-gif@3.1.6 (installed, enabled)
  * nodebb-rewards-essentials@1.0.0 (installed, enabled)
  * nodebb-theme-harmony@1.2.49 (installed, disabled)
  * nodebb-theme-lavender@7.1.8 (installed, disabled)
  * nodebb-theme-peace@2.2.4 (installed, disabled)
  * nodebb-theme-persona@13.3.14 (installed, enabled)
  * nodebb-theme-slick@2.0.2 (installed, disabled)
  * nodebb-theme-vanilla@12.1.19 (installed, disabled)
  * nodebb-widget-essentials@7.0.15 (installed, enabled)
- **Database type:** mongo, redis
- **Database version:** mongo v7.0.9, redis v=7.0.15

I  tried to uninstall, reinstall e re-enabled it but the problem persists.

I've noticed during ./nodebb restart -l these messages:

`warn: [plugins] File not found: /var/www/nodebb/node_modules/nodebb-plugin-customize/build/public/lib/index.js (Ignoring)`
`warn: [helpers.setupAdminPageRoute(/admin/plugins/customize)] passing `middleware` as the third param is deprecated, it can now be safely removed`

**Comment by ylothar** [comment]
@pitaj I have tried several times to uninstall and reinstall the plugin both from the command line and via web UI but the result is always the same.
My custom translations that are shown in the plugin admin page are not applied.
I've noticed that with Firefox on console when I load plugin admin page I've got this warnig:
![nodebb](https://github.com/NodeBB/nodebb-plugin-customize/assets/682247/7f25764a-ed3b-4cf4-800a-dbc11b6a5bc8)
Can I do some more tests or give you other information that may help you understand the problem?

**Comment by pitaj** [comment]
Can you try downgrading to version 4.0.1 of the plugin?

**Comment by ylothar** [comment]
Version 4.0.1 seems OK. I also tried 4.0.0 and it's OK too. Versions 3.0.0 and 4.0.2 seem to have problems.

**Comment by pitaj** [comment]
Alright. Use 4.0.1 for now. We'll have to re-release 4.0.2 (the only thing it added was Polish translations I think)

**Comment by ylothar** [comment]
Thank you @pitaj for you support!

**Comment by pitaj** [comment]
fixed in 4.0.3
