### ISSUE TITLE
plugin does not work with 1.13.2

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-plugin-customize#2]
We have NodeBB 1.13.2, plugin does not work and there is nothing on the logs...

the current version of the plugin is installed with:
npm  6.14.4
node  v12.16.3 (upgraded to 13.14.0 but still does not work)
graceful-fs 4.2.4

But it does not work or give any error even in development mode... 
we deleted all plugins except these in the picture but still, it does not work: 

![Screen Shot 2020-05-07 at 3 32 31 PM](https://user-images.githubusercontent.com/52054408/81336859-1326b300-9078-11ea-827c-55cd6a1385af.png)

I changed the order of plugins but still does not work... What else can we try?

**Comment by pitaj** [comment]
I'm not able to reproduce. What flow are you using to create customizations?

For reference, here's a screenshot of the plugin page
![image](https://user-images.githubusercontent.com/803701/81358623-4b3bef00-9094-11ea-90a2-659f63fdecbc.png)

After setting that up, I clicked the build button in the bottom right, and then rebuilt and restarted nodebb. After doing so, my 404 page showed exactly as expected:

![image](https://user-images.githubusercontent.com/803701/81358730-89d1a980-9094-11ea-8fe0-3cbcd42a52a6.png)

And "System Default Language" shows up where it should:

![image](https://user-images.githubusercontent.com/803701/81358778-acfc5900-9094-11ea-8e96-dce35725a25d.png)

Here's my plugin order panel:

![image](https://user-images.githubusercontent.com/803701/81358811-c30a1980-9094-11ea-81bc-20573e2e175e.png)

**Comment by AliCihan** [comment]
Hi @pitaj , thanks a lot... however no change...

we are currently on Debian 9... do you think it will be fixed if we upgrade to Debian 10?

In our development forum, we did trials... In our first trial, this plugin worked beautifully when we upgraded our forum from 1.12.2 to 1.13.2 ... However this was for development... 

Later, for our prod server; we rebuild a server and installed fresh nodebb (1.13.2) with our backed up databases, uploads etc. (this was our plan independent of this topic for other reasons)... 
However in this fresh start, customize plugin did not work at all... Although all other plugins were working... Nothing in the logs...  

We are wondering, why it was working with a direct upgrade? But not with a fresh start... Any idea?

**Comment by pitaj** [comment]
I have no idea why it wouldn't work for you. What version of node are you on?

Can you try adding a new customization following my steps exactly and tell me how it goes?

**Comment by AliCihan** [comment]
we have solved the problem by upgrading from Debian 9 to Debian 10... Everything else stayed the same version (node/npm/NodeBB)... Nothing else helped... FYI...
