### ISSUE TITLE
Template customization does not work/apply.

### ISSUE THREAD

**Issue by gggdunlix** [NodeBB/nodebb-plugin-customize#3]
When using this plugin, after editing one of the HTML Templates, the Green checkmark button does nothing when clicking, and neither does the blue wrench button.  When clicking the grey edit button, the edits aren't there anymore, even without reloading. I've tried rebuilding after editing. This shows up in Dev Tools console tab when clicking the blue button:
![image](https://user-images.githubusercontent.com/33298379/111238209-04305b80-85cd-11eb-8f13-b0ee3330e84b.png)

**Comment by pitaj** [comment]
Fixed in v2.0.0, which require NodeBB 1.17.0
