### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by ylothar** [NodeBB/nodebb-plugin-customize#4]
When I try to modify a Translation Customizations check box seems not to activate and when I click to compile icon I get Error message (see screenshot).
In the log I get:
```
2021-08-30T13:25:17.438Z [4567/18371] - [31merror[
39m: /talk/api/admin/plugins/customize/build
invalid csrf token
```
![nodebb01](https://user-images.githubusercontent.com/682247/131346662-bbfa2202-6f14-4d71-935c-987fa8fb85b4.png)
![nodebb02](https://user-images.githubusercontent.com/682247/131346722-8576189c-c58c-434c-93c3-cbe890bd71f5.png)

**Comment by ylothar** [comment]
NodeBB v1.18.0
nodebb-plugin-customize 1.1.2

**Comment by pitaj** [comment]
The latest version of this plugin is 2.0.0
Please try updating

**Comment by ylothar** [comment]
Thank you, now it works.
NodeBB seems to show v1.1.2 as the latest release, even after manually updating:
![Schermata da 2021-08-30 17-38-54](https://user-images.githubusercontent.com/682247/131365763-8a24b235-4e74-43ab-9003-d5a84ff9e299.png)

**Comment by pitaj** [comment]
Gonna reopen this as a reminder to update the compatibility.
